name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.202"

      - name: Lint using dotnet format
        uses: coherence/action-dotnet-format-check@v1

      - name: Build dotnet project
        run: dotnet build src/

      - name: Test dotnet project
        run: dotnet test src/
