on:
  push:
    tags:
      - "v*"

name: Upload nuget package
jobs:
  release:
    name: Create and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dotnet core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.202"

      - name: Fetch version
        id: fetchver
        uses: coherence/action-version-from-tag@v1

      - name: Pack specific version
        uses: coherence/action-nuget-pack-push@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          workspace: src/lib/
          version: ${{ steps.fetchver.outputs.version }}
